project:
  type: website
  output-dir: docs

website:
  title: "Lauren E. Flynn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: publications.qmd
      - href: resources.qmd



format:
  html:
    theme: 
      - pulse
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet"> 
    toc: true
    mainfont: "Roboto"



